export function buildPRBody(
  patchInfo: { bugSummary: string; description: string },
  stackTraceInfo: {
    filePath: string;
    lineNumber: number;
    errorMessage: string;
    errorType: string;
  }
): string {
  return `
## [AI Fix] Bug Fix

### Summary
${patchInfo.bugSummary}

### Description
${patchInfo.description}

### Error Details
- **Type**: ${stackTraceInfo.errorType}
- **Message**: ${stackTraceInfo.errorMessage}
- **File**: \`${stackTraceInfo.filePath}\`
- **Line**: ${stackTraceInfo.lineNumber}

### Changes
This PR automatically fixes the bug identified in the stack trace.

---
*This PR was automatically generated by Bug-to-PR Agent*
    `.trim();
}
